services:
  # api:
  #   build: ./api
  #   container_name: api
  #   depends_on:
  #     - db
  #   env_file: ../.env
  #   networks:
  #     - app-network
  #   ports:
  #     - 2000:80
  #   volumes:
  #     - api:/app

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app-network


##    NETWORKS    ##

networks:
  app-network:
    driver: bridge



##    VOLUMES    ##

volumes:
  database: {}
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: /lib/myapp/data

  api:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./api/