services:
  # api:
  #   build: ./api
  #   container_name: api
  #   depends_on:
  #     - db
  #     - redis
  #   env_file: .env
  #   networks:
  #     - db_network
  #     - redis_network
  #   # ports:
  #   #   - 8080:80
  #   volumes:
  #     - api_srcs:/app

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
      - redis_network
    ports:
      - 6370:6379

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - db_network

##    NETWORKS    ##

networks:
  db_network:
    driver: bridge

  redis_network:
    driver: bridge



##    VOLUMES    ##

volumes:
  database: {}
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: /lib/myapp/data

  api_srcs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./api/srcs