services:
  eapi:
    build:
      context: ../api
      dockerfile: docker/Dockerfile.tests
    container_name: eapi
    depends_on:
      - db
    env_file: ../.env
    tty: true
    environment:
      - POSTGRES_HOST=db
    networks:
      - db_network