services:
  eapi:
    build:
      context: ../api
      dockerfile: docker/Dockerfile.tests
    container_name: eapi
    tty: true
    depends_on:
      - db
    env_file: ../.env
    environment:
      - POSTGRES_HOST=db
    networks:
      - db_network
    command: bash -c "cargo test && echo 'cargo test done!' && cargo clippy && echo 'cargo clippy done!' && cargo fmt --check && echo 'cargo fmt --check done!'"