FROM rust:1.90 AS builder
WORKDIR /usr/src/eapi

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/* && \
    rustup component add clippy && \
    rustup component add rustfmt

# Cache dependencies
COPY ./Cargo.toml ./tools/dummy.rs ./
RUN sed -i 's#src/main.rs#dummy.rs#' Cargo.toml
RUN cargo check && \
    cargo build && \
    cargo test --no-run
RUN sed -i 's#dummy.rs#src/main.rs#' Cargo.toml && rm ./dummy.rs

COPY . .
RUN chmod +x ./tools/entrypoint.sh

ENTRYPOINT ["./tools/entrypoint.sh"]
CMD ["bash", "-c", "cargo test && echo 'cargo test done!'"]
# CMD ["bash", "-c", "\
#     cargo test && echo 'cargo test done!' && \
#     cargo clippy && echo 'cargo clippy done!' && \
#     cargo fmt --check && echo 'cargo fmt --check done!'\
# "]
