services:
  backend:
    build: backend
    container_name: backend
    env_file: backend/srcs/.env

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp
    ports:
      - "5432:5432"
    networks:
      - app-network


##    NETWORKS    ##

networks:
  app-network:
    driver: bridge



##    VOLUMES    ##

volumes:
  database: {}