services:
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    env_file: ../.env
    networks:
      - app-network
    ports:
      - 2000:80
    volumes:
      - backend:/app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - frontend:/app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app-network


##    NETWORKS    ##

networks:
  app-network:
    driver: bridge



##    VOLUMES    ##

volumes:
  database: {}
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: /lib/myapp/data

  frontend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./frontend/srcs
  

  backend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./backend/srcs