services:
  # backend:
  #   build: backend
  #   container_name: backend
  #   env_file: backend/srcs/.env

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    # networks:
    #   - app-network


##    NETWORKS    ##

networks:
  app-network:
    driver: bridge



##    VOLUMES    ##

volumes:
  database: {}