FROM rust:1.90 AS builder

WORKDIR /usr/src/eapi

RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

RUN	rustup component add clippy
RUN	rustup component add rustfmt

# Caching dependencies
COPY ./srcs/Cargo.toml ./tools/dummy.rs ./
RUN sed -i 's#src/main.rs#dummy.rs#' Cargo.toml && \
	cargo check && \
	cargo build && \
	cargo test --no-run && \
	sed -i 's#dummy.rs#src/main.rs#' Cargo.toml && \
	rm ./dummy.rs

COPY ./migrations ../migrations

COPY ./tools/entrypoint.sh /
RUN chmod +x /entrypoint.sh

COPY ./srcs .

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bash", "-c", "\
cargo test && echo cargo test done ! &&\
cargo clippy && echo cargo clippy done ! &&\
cargo fmt --check && echo cargo fmt --check done !\
"]