name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: make test

  clippy:
    name: Check linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve Rust cache
        uses: Swatinem/rust-cache@v2
        with:
            workspaces: "./api"

      - name: Set up Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Check linting
        working-directory: ./api
        run: cargo clippy

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retrieve Rust cache
        uses: Swatinem/rust-cache@v2
        with:
            workspaces: "./api"

      - name: Set up Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Run cargo fmt
        working-directory: ./api
        run: cargo fmt --check