name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Starting Containers
      run: docker compose up -d
    - name: Installing sqlx-cli
      run: cargo install sqlx-cli --verbose
    - name: Running migrations
      run: cargo sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
